// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmmJ7UyPFspGw0fYdvJ8nXIxngvMQyDM',
    appId: '1:752748936745:web:a20c26e16ae8f9c8e9a638',
    messagingSenderId: '752748936745',
    projectId: 'aggregates-app',
    authDomain: 'aggregates-app.firebaseapp.com',
    storageBucket: 'aggregates-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9NXRGdQ7-aKrN5_vlaH4JcUG_GBcigQ',
    appId: '1:752748936745:android:156181a0e7ad3697e9a638',
    messagingSenderId: '752748936745',
    projectId: 'aggregates-app',
    storageBucket: 'aggregates-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGVlz74r7xoplPpMuOj6lbZfzU5behNlA',
    appId: '1:752748936745:ios:953951f88e6f2777e9a638',
    messagingSenderId: '752748936745',
    projectId: 'aggregates-app',
    storageBucket: 'aggregates-app.firebasestorage.app',
    iosClientId: '752748936745-tk5gkn61pegkc4hnkdu8ug7m3b0ehei5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aggregatesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGVlz74r7xoplPpMuOj6lbZfzU5behNlA',
    appId: '1:752748936745:ios:953951f88e6f2777e9a638',
    messagingSenderId: '752748936745',
    projectId: 'aggregates-app',
    storageBucket: 'aggregates-app.firebasestorage.app',
    iosClientId: '752748936745-tk5gkn61pegkc4hnkdu8ug7m3b0ehei5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aggregatesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmmJ7UyPFspGw0fYdvJ8nXIxngvMQyDM',
    appId: '1:752748936745:web:a507a83b6fb6f793e9a638',
    messagingSenderId: '752748936745',
    projectId: 'aggregates-app',
    authDomain: 'aggregates-app.firebaseapp.com',
    storageBucket: 'aggregates-app.firebasestorage.app',
  );
}
